sample_proj:
  target: modal
  outputs:
    modal:
      type: sqlite
      threads: 1
      schema: "main"
      database: "database" # required but has no meaning for sqlite
      schemas_and_paths:
        main: "{{ env_var('MAIN_DB_PATH') }}"
        jaffle_shop: "{{ env_var('RAW_DB_PATH') }}"
      schema_directory: "{{ env_var('OUTPUT_SCHEMAS_PATH') }}"
    local:
      type: sqlite
      threads: 1
      schema: "main"
      database: "database"
      schemas_and_paths:
        main: "dbs/main.db"
        jaffle_shop: "../../meltano/meltano_project/jaffle_shop_raw.db"
      schema_directory: "dbs/"
