name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy example apps
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-20.04
    env:
      MODAL_TOKEN_ID: ${{ secrets.MODAL_MODAL_LABS_TOKEN_ID }}
      MODAL_TOKEN_SECRET: ${{ secrets.MODAL_MODAL_LABS_TOKEN_SECRET }}
      MODAL_ENVIRONMENT: main

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Modal client package and jupytext
        run: pip install modal-client jupytext pydantic~=1.10

      - name: Run deployment script
        run: |
          python3 internal/deploy.py --no-dry-run
